### PR TITLE
httpd24 2.4.23

### PR DESCRIPTION
**Pull request by kabel**

### CODE REVIEW

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by kabel** [comment]
One of these days that bot will give you the answer you're looking for 😉

**Comment by javian** [comment]
@kabel yes!! =) We're having some issues with the build bot so that's why I had to rerun it a few times but I'm hoping we can get this merged within the next couple of days.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@kabel thanks for the submission !

**Pull request closed without merging**
