### PR TITLE
httpd24 2.4.26

### PR DESCRIPTION
**Pull request by kabel**

### CODE REVIEW

**Comment by kabel** [comment]
@javian The test failure is coming from a relatively [new audit](https://github.com/Homebrew/brew/commit/3011cbac34334c37eba20cbf06fe7942522602f6). The `apr-util` option `with-openldap` is absolutely necessary if building with the `with-ldap` option, so I'm not sure what the workaround is for this.

**Comment by javian** [comment]
@kabel That will have to do for now and it should be able to merge. There are ways to work around it but the only option right now seems to be to vendor apr-util into the formula itself as a resource which can be done but that can be changed later.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks @kabel !

**Pull request closed without merging**
