### PR TITLE
Update to Apache 2.2.32 and 2.4.26

### PR DESCRIPTION
**Pull request by capripot**
https://httpd.apache.org/download.cgi

Stable Release - Latest Version:
- 2.4.26 (released 2017-06-19)

Legacy Release - 2.2 Branch:
- 2.2.32 (released 2017-01-13)

### CODE REVIEW

**Comment by javian** [comment]
Can you please submit these as seperate PRs and use the method described here https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#submit-a-version-upgrade-for-the-foo-formula ?

**Comment by javian** [comment]
Please also have a look at the build errors reported by jenkins CI and see if you can fix them. I'd be happy to help if you need any support.

**Comment by capripot** [comment]
I bump into a lot of unrelated problems, is that new constraints put in place by homebrew-core post publication of this package?

**Comment by capripot** [comment]
Closing in favor of #167 and #166

**Pull request closed without merging**
