### PR TITLE
Downgrade httpd24 to v 2.4.16

### PR DESCRIPTION
**Pull request by madhancock**
Ref: #95

### CODE REVIEW

**Comment by bfontaine** [comment]
Homebrew doesn’t support downgrading versions. Can’t we apply a patch instead?

**Comment by madhancock** [comment]
Doesn't look like there is one available. It should be fixed in 2.4.18, so I guess Apache 2.4 on homebrew is broken for the time being. When making this change I was thinking of it more as a preventative measure (preventing people from upgrading to or installing 2.4.17) rather than remedial. That said I'm not sure how homebrew would handle the change if you happen to already be on 2.4.17 - if its silently ignores it then I don't see a problem, but if it kicks up a fuss then its not a workable solution.

**Comment by bfontaine** [comment]
> if its silently ignores it then I don't see a problem

Yeah it’ll silently ignores it.

**Comment by madhancock** [comment]
In that case I think it would make sense to merge the changes to keep those not on v 2.4.17 on v 2.4.16 until v 2.4.18 arrives with the patch.

**Comment by bfontaine** [comment]
Yeah that makes sense. Could you by any chance fix the failing test so we could pull bottles?

**Comment by madhancock** [comment]
3/6 errors are `* Non-executables were installed to "/usr/local/Cellar/httpd24/2.4.16/bin"`, similar to  https://github.com/Homebrew/homebrew/issues/16177 so they can likely be ignored.

The other 3 failures are `brew test --verbose homebrew/apache/httpd24` failing. However this command fails on every homebrew installation of apache 2.4 in my office so I think both of these check failures are invalid for this particular package.

**Comment by bfontaine** [comment]
You can fix the test by using `bin` instead of `sbin`.

**Comment by madhancock** [comment]
At the risk of sounding like an idiot, how do I do that? Is that something that can be changed in this project itself or something configured in Jenkins?

**Comment by bfontaine** [comment]
Yeah you have to edit the formula file; just like you did to change the version.

At the bottom change this:

```rb
   test do
     system sbin/"httpd", "-v"
   end
```

into this:

```rb
   test do
     system bin/"httpd", "-v"
   end
```

**Comment by madhancock** [comment]
Thanks, I'll use both eyes next time! 

Just the `Non-executables were installed to "/usr/local/Cellar/httpd24/2.4.16/bin"` errors remain now so should be good to go.

**Comment by bfontaine** [comment]
Thank you @madhancock for your contribution; we appreciate it! :tada:

**Comment by madhancock** [comment]
NP @bfontaine, lets keep our eye peeled for 2.4.18 in the coming weeks!

**Comment by RandomDSdevel** [comment]
@madhancock, @bfontaine:  Just wanted to note that, for those who installed HTTPD 2.4.17 before HTTPD's formula was reverted back to serving v2.4.16 here, `brew doctor -vd` issues the following warning:  
```
Warning: Skipping homebrew/apache/httpd24: most recent version 2.4.16 not installed
```
Given that this is just a _warning_, it is safe for me to ignore this for now, right?

**Comment by bfontaine** [comment]
@RandomDSdevel Yeah this is just a temporary situation until they release HTTPD 2.4.18.

**Comment by RandomDSdevel** [comment]
Cool, thanks.

**Pull request closed without merging**
