### PR TITLE
Add formula for mod_rpaf

### PR DESCRIPTION
**Pull request by lukasbestle**
I'm currently setting up Apache behind a reverse-proxy on my machine, so I need mod_rpaf.
This is the formula installing that module. Please let me know if something is missing.

### CODE REVIEW

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by alanthing** [comment]
(apologies on the delay, I am planning on investing time into homebrew-apache issues and PRs this weekend)

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@lukasbestle Hi Lukas - would you still want to add this apache module to homebrew ? If so you need to start by removing the sha1 hash in the Formula.

**Comment by lukasbestle** [comment]
Sure. I have also squashed my commits.

**Comment by javian** [comment]
Thanks @lukasbestle ! It seems like there are a few more things that needs to be adjusted.
```
Error: 8 problems in 1 formula
homebrew/apache/mod_rpaf:
  * A `test do` test block should be added
  * Formula should have a desc (Description).
  * `require "formula"` is now unnecessary
  * C: 28: col 66: Use `&&` instead of `and`.
  * C: 30: col 37: Use `&&` instead of `and`.
  * C: 38: col 46: Prefer double-quoted strings inside interpolations.
  * C: 44: col 46: Prefer double-quoted strings inside interpolations.
  * C: 78: col 1: Extra empty line detected at class body end.
```
It is also failing due to the apr-1-config/apxs/libtool but I'm not sure how to get around that at the moment.

**Comment by lukasbestle** [comment]
Everything besides the test block should be fixed. Other homebrew-apache formulae don't have tests either, so it should be fine?

**Comment by lukasbestle** [comment]
Regarding the build error: When I first built this formula, I had to copy or symlink some files to somewhere. It's too long ago however to still remember what exactly was needed. There's no automatic fix that can be done by Homebrew though.

**Comment by javian** [comment]
Yes that is correct - the software that comes with OSX is bugged and require you to make an adjustment at the moment (documented on the homebrew-apache page) and homebrew currently doesn't work around it. If you work with the homebrew apache it should compile just fine but since that's not the default setting it breaks unless you provide additional parameters.

**Comment by lukasbestle** [comment]
Yep. I have just tested the formula locally and (when using the Homebrew httpd24) get the following error:

```
apxs:Error: /usr/local/Cellar/apr/1.5.2/libexec/bin/apr-1-config not found!.
```

The actual path should be `/usr/local/Cellar/apr/1.5.2_1/libexec/bin/apr-1-config`, but I don't know where in the build process the wrong path is built and where it comes from.

**Comment by javian** [comment]
@lukasbestle you need to update homebrew since that apr revision is not the latest one - you need 1.5.2_2. That should fix that issue.

**Comment by lukasbestle** [comment]
Yes, it works now. So is there anything I need to change before you can merge this?

**Comment by javian** [comment]
No I think it should be fine. The build system won't work and it can be verified in other ways so. Thanks for the submission!

**Comment by lukasbestle** [comment]
Thanks for merging!

**Pull request closed without merging**
