### PR TITLE
Support for macOS Sierra

### PR DESCRIPTION
**Pull request by rayfaddis**

### CODE REVIEW

**Comment by ksom** [comment]
Thanks !

**Comment by JacopKane** [comment]
Unfortunately this didn't solve problems for me

```
Last 15 lines from /Users/furkantunali/Library/Logs/Homebrew/httpd24/02.make:
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=compile clang  -g -O2      -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10     -I. -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/os/unix -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/include -I/usr/local/opt/apr/libexec/include/apr-1 -I/usr/local/opt/apr-util/libexec/include/apr-1 -I/usr/local/Cellar/pcre/8.39/include -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/aaa -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/cache -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/core -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/database -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/filters -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/ldap -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/server -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/loggers -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/lua -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/proxy -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/session -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/ssl -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/test -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/server -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/arch/unix -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/dav/main -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/generators -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/mappers  -prefer-non-pic -static -c rotatelogs.c && touch rotatelogs.lo
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=compile clang  -g -O2      -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10     -I. -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/os/unix -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/include -I/usr/local/opt/apr/libexec/include/apr-1 -I/usr/local/opt/apr-util/libexec/include/apr-1 -I/usr/local/Cellar/pcre/8.39/include -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/aaa -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/cache -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/core -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/database -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/filters -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/ldap -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/server -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/loggers -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/lua -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/proxy -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/session -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/ssl -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/test -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/server -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/arch/unix -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/dav/main -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/generators -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/mappers  -prefer-non-pic -static -c checkgid.c && touch checkgid.lo
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=compile clang  -g -O2      -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10     -I. -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/os/unix -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/include -I/usr/local/opt/apr/libexec/include/apr-1 -I/usr/local/opt/apr-util/libexec/include/apr-1 -I/usr/local/Cellar/pcre/8.39/include -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/aaa -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/cache -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/core -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/database -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/filters -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/ldap -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/server -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/loggers -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/lua -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/proxy -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/session -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/ssl -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/test -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/server -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/arch/unix -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/dav/main -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/generators -I/private/tmp/httpd24-20160919-14322-1wtlb66/httpd-2.4.23/modules/mappers  -prefer-non-pic -static -c fcgistarter.c && touch fcgistarter.lo
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=link clang  -g -O2         -o htdigest  htdigest.lo      /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=link clang  -g -O2         -o logresolve  logresolve.lo      /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=link clang  -g -O2         -o httxt2dbm  httxt2dbm.lo      /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread
libtool: link: cannot find the library `/usr/local/Cellar/apr/1.5.2_2/libexec/lib/libapr-1.la' or unhandled argument `/usr/local/Cellar/apr/1.5.2_2/libexec/lib/libapr-1.la'
make[2]: *** [htdigest] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: link: cannot find the library `/usr/local/Cellar/apr/1.5.2_2/libexec/lib/libapr-1.la' or unhandled argument `/usr/local/Cellar/apr/1.5.2_2/libexec/lib/libapr-1.la'
make[2]: *** [logresolve] Error 1
libtool: link: cannot find the library `/usr/local/Cellar/apr/1.5.2_2/libexec/lib/libapr-1.la' or unhandled argument `/usr/local/Cellar/apr/1.5.2_2/libexec/lib/libapr-1.la'
make[2]: *** [httxt2dbm] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by javian** [comment]
@JacopKane  If you `brew reinstall -s apr-util` first it should work. I'm waiting for the apr-util revision update to be merged with core to fix it in the bottle but before that you need to fix it manually.

**Comment by javian** [comment]
And also to note that I can't merge this since it doesn't compile on Sierra in the stock system so we need to make some further changes to the code for it to work.

**Comment by javian** [comment]
Awaiting merge https://github.com/Homebrew/homebrew-core/pull/4943

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Merged #135 which provides the same functionality.

**Pull request closed without merging**
