### PR TITLE
httpd22 2.2.32

### PR DESCRIPTION
**Pull request by capripot**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by javian** [comment]
Can you fix this audit error ? ` * C: 106: col 3: Please set plist_options when using a formula-defined plist.`

**Comment by capripot** [comment]
Fixed it, thanks for the feedback

**Comment by javian** [comment]
Looking at the CI it seems that the test is failing. It looks like its using sbin/httpd but I couldn't find that the Formula put the httpd binary in `sbin` - can you double check that and change it to `bin` if appropriate ?

**Comment by capripot** [comment]
I fixed the test path. I'm not sure what to do about these remaining errors.
- For the non-executables put in `/usr/local/opt/httpd22/bin/`, should we add execution privileges to them? Not sure of the repercussions.
- About the Headers I would say it should be a `keg-only` package that user needs to link after install. 
What do you think?

**Comment by javian** [comment]
httpd24 isn't keg only and that doesn't show the error so it shouldn't be needed. As far as the envvars files go there seems to be some code in the httpd24 formula that mitigates that issue.

**Comment by capripot** [comment]
I can surely remove `keg_only` option, but then it will not pass the audit.

```
$ brew audit httpd22
homebrew/apache/httpd22:
  * Header files that shadow system header files were installed to "/usr/local/opt/httpd22/include"
    The offending files are:
      /usr/local/opt/httpd22/include/apache2/ap_compat.h
      /usr/local/opt/httpd22/include/apache2/ap_config.h
      /usr/local/opt/httpd22/include/apache2/ap_config_auto.h
      /usr/local/opt/httpd22/include/apache2/ap_config_layout.h
      /usr/local/opt/httpd22/include/apache2/ap_listen.h
      /usr/local/opt/httpd22/include/apache2/ap_mmn.h
      /usr/local/opt/httpd22/include/apache2/ap_mpm.h
      /usr/local/opt/httpd22/include/apache2/ap_provider.h
      /usr/local/opt/httpd22/include/apache2/ap_regex.h
      /usr/local/opt/httpd22/include/apache2/ap_regkey.h
      /usr/local/opt/httpd22/include/apache2/ap_release.h
      /usr/local/opt/httpd22/include/apache2/http_config.h
      /usr/local/opt/httpd22/include/apache2/http_connection.h
      /usr/local/opt/httpd22/include/apache2/http_core.h
      /usr/local/opt/httpd22/include/apache2/http_log.h
      /usr/local/opt/httpd22/include/apache2/http_main.h
      /usr/local/opt/httpd22/include/apache2/http_protocol.h
      /usr/local/opt/httpd22/include/apache2/http_request.h
      /usr/local/opt/httpd22/include/apache2/http_vhost.h
      /usr/local/opt/httpd22/include/apache2/httpd.h
      /usr/local/opt/httpd22/include/apache2/mod_auth.h
      /usr/local/opt/httpd22/include/apache2/mod_cgi.h
      /usr/local/opt/httpd22/include/apache2/mod_core.h
      /usr/local/opt/httpd22/include/apache2/mod_dav.h
      /usr/local/opt/httpd22/include/apache2/mod_dbd.h
      /usr/local/opt/httpd22/include/apache2/mod_include.h
      /usr/local/opt/httpd22/include/apache2/mod_log_config.h
      /usr/local/opt/httpd22/include/apache2/mod_proxy.h
      /usr/local/opt/httpd22/include/apache2/mod_rewrite.h
      /usr/local/opt/httpd22/include/apache2/mod_ssl.h
      /usr/local/opt/httpd22/include/apache2/mod_status.h
      /usr/local/opt/httpd22/include/apache2/mpm_common.h
      /usr/local/opt/httpd22/include/apache2/os.h
      /usr/local/opt/httpd22/include/apache2/scoreboard.h
      /usr/local/opt/httpd22/include/apache2/unixd.h
      /usr/local/opt/httpd22/include/apache2/util_cfgtree.h
      /usr/local/opt/httpd22/include/apache2/util_charset.h
      /usr/local/opt/httpd22/include/apache2/util_ebcdic.h
      /usr/local/opt/httpd22/include/apache2/util_filter.h
      /usr/local/opt/httpd22/include/apache2/util_ldap.h
      /usr/local/opt/httpd22/include/apache2/util_md5.h
      /usr/local/opt/httpd22/include/apache2/util_script.h
      /usr/local/opt/httpd22/include/apache2/util_time.h
      /usr/local/opt/httpd22/include/apache2/util_xml.h
Error: 1 problem in 1 formula
```

**Comment by javian** [comment]
The httpd24 formula has a different `includedir:    ${prefix}/include/apache2` . Can you try replacing apache2 with httpd ? macOS uses the apache2 directory name and hence the clash in the audit. Not certain what kind of effects this will have though but at least the cause has been identified.

**Comment by javian** [comment]
Thanks for the effort @capripot !

**Pull request closed without merging**
