### PR TITLE
httpd24: Clean up plist related caveats

### PR DESCRIPTION
**Pull request by kabel**
The generic caveats from brew will include the necessary information for
starting a plist.

### CODE REVIEW

**Comment by kabel** [comment]
Bump. Anybody have time to look at this? All pull requests to httpd will fail the audit until this is merged.

**Comment by kabel** [comment]
@bfontaine I hate to be a pest, but is there any way to help move this tap along? It seems to have fallen off the maintainers' radar.

**Comment by mistydemeo** [comment]
Thanks! Sorry for the lack of response.

**Comment by bfontaine** [comment]
Thanks Misty!

**Pull request closed without merging**
