### PR TITLE
apr: migrating to Homebrew/Homebrew

### PR DESCRIPTION
**Pull request by DomT4**
Migrating the apr formulae to Homebrew/Homebrew to allow us to deal with the needs-CLT issue. The CLT is a big package, and if people don't need everything in it, asking them to install it isn't necessarily the best user experience we could deliver.

See https://github.com/Homebrew/homebrew/pull/34987

### CODE REVIEW

**Comment by alanthing** [comment]
Apologies for the delay- holidays. I'll test this on Monday if that's alright.

**Comment by DomT4** [comment]
No worries, understand entirely :+1:

**Comment by alanthing** [comment]
Reviewing your apr formula in the main Homebrew PR versus these homebrew-apache formulae. I'll report back soon.

**Comment by alanthing** [comment]
Tested successfully: ab, httpd22, httpd24, mod_security. It'd be great to see Homebrew/homebrew/pull/34987 merged ASAP because some formulae here won't work until then.

**Comment by DomT4** [comment]
Mike merged it about a half hour ago, so we should be golden now. Cheers for checking everything over on this side! :+1:

**Pull request closed without merging**
